---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone-project
  template:
    metadata:
      labels:
        app: capstone-project
    spec:
      containers:
      - name: capstone-project-container
        image: emined/projectimage
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: capstone-project-service
spec:
  selector:
    app: capstone-project
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 5000
      nodePort: 30000
  type: LoadBalancer
